### ISSUE TITLE
Upload broken in Firefox on Mac

### ISSUE THREAD

**Issue by nedmas** [unclecheese/Uploadify#15]
Hi there,

I've been using this plugin for a while and its awesome! However I noticed today that I can't upload files when I use Firefox. When I click on the 'Change' button in the 'Add files to ' dialog the file explorer fails to open. The only thing that happens is that the 'Change' button does a little jump to the right and then pops back.

Any suggestions on how to work around this would be great as one of my clients currently uses firefox and so can't upload any images!

Thanks

**Comment by helion** [comment]
I'm experiencing a similar problem with Firefox 5.0 on Windows 7 and up to date versions of Silverstripe, DOM, and Uploadify as of August, 2nd.

I have a HasMany association to a set of images and when, in the admin, I mouse over 'Add Files' -> 'Upload Files' I get the rollover effect but my cursor turns into the text cursor and clicking selects the link text. Everything works correctly in Safari 5.1.

When I have a chance I'll apply any available updates and do what troubleshooting I can and report back with the results.

**Comment by beccablumm** [comment]
I've been battling with the uploadify field in a front-end form on FireFox (mac / snow leopard). If I set a height style for the uploadify object in my stylesheet (#Form_ApplyForm_AttachedFilesUploader { height: 30px; }), the button works. Note that I was not having any problems with Safari, Chrome or Opera on the same platform. Not tested on windows or any other platforms yet...
